name: number_to_iraqi_words
description: Convert numbers to Iraqi Arabic words in Dart.
version: 1.0.0
homepage: https://github.com/zain313/number_to_iraqi_words

# repository: https://github.com/zain313/number_to_iraqi_words

environment:
  sdk: '>=2.17.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
